name: Streetshots
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.683277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#88211c'
    - '#e2e2e2'
    - '#3c4c66'
    - '#91937e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
