name: Streetshots
favicon: null
layout_spectrum: 0.7597
typography_spectrum: 0.48514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.9375
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
